/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// import java.awt.event.ActionEvent;
// import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author This Pc
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDot = new javax.swing.JButton();
        btnOne2 = new javax.swing.JButton();
        btnSeven1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        answer = new javax.swing.JTextField();
        btnZero = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDoubleZero = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        allClear = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        PlusMinus = new javax.swing.JButton();

        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnOne2.setText("1");
        btnOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOne2ActionPerformed(evt);
            }
        });

        btnSeven1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeven1.setText("7");
        btnSeven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeven1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        answer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        answer.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        answer.setText("000");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnDoubleZero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDoubleZero.setText("00");
        btnDoubleZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleZeroActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btndot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndot.setText(".");
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });

        btnOne.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        allClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allClear.setText("AC");

        allClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        PlusMinus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PlusMinus.setText("+/-");
        PlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(answer)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(allClear,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        0, Short.MAX_VALUE)
                                                                                .addGap(10, 10, 10))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(btnOne,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(btndot,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        69,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(clear,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        65,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(PlusMinus,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        65,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(btnDivide,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        65,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(2, 2, 2))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnZero,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addComponent(btnDoubleZero,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0, Short.MAX_VALUE)
                                                                                        .addComponent(btnThree,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                65, Short.MAX_VALUE))
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(btnPlus,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(12, 12, 12)
                                                                                                .addComponent(btnEqual,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE))))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(btnSeven,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(btnFour,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                65, Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addComponent(btnEight,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                63, Short.MAX_VALUE)
                                                                                        .addComponent(btnFive,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addComponent(btnSix,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                65, Short.MAX_VALUE)
                                                                                        .addComponent(btnNine,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(btnMinus,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(btnMultiply,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnTwo,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        63,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                                .addGap(11, 11, 11)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 68,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PlusMinus, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(allClear, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btndot, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                        .addComponent(btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnZero, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDoubleZero, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkInput() {
        try {
            @SuppressWarnings("unused")
            double n = Double.parseDouble(answer.getText());
        } catch (Exception e) {
            return false;
        }
        return true;
    }

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDotActionPerformed

        answer.setText(answer.getText() + ".");
    }

    private void btnDoubleZeroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDoubleZeroActionPerformed

        answer.setText(answer.getText() + "00");
    }

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEqualActionPerformed

        if (checkInput()) {
            if (opretion == 1) {
                current = Double.parseDouble(answer.getText());
                current = current + previous;
                answer.setText((current) + "");
                previous = 0;
                // current = 0;
            } else if (opretion == 2) {
                current = Double.parseDouble(answer.getText());
                current = previous - current;
                answer.setText((current) + "");
                previous = 0;
            } else if (opretion == 3) {
                current = Double.parseDouble(answer.getText());
                current = current * previous;
                answer.setText((current) + "");
                previous = 0;

            } else if (opretion == 4) {

                current = Double.parseDouble(answer.getText());
                if (current == 0) {
                    answer.setText("Cann't divide by zero !");
                } else {
                    current = previous / current;
                    answer.setText((current) + "");
                    previous = 0;
                }
            }
            opretion = 0;
        } else {
            answer.setText("Enter Valid Inputs");
        }

    }

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "0");

    }

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "3");

    }

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "2");

    }

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btndotActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + ".");

    }

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "1");

    }

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        if (checkInput()) {
            switch (opretion) {
                case 1:
                    current = Double.parseDouble(answer.getText());
                    previous = previous + current;

                    answer.setText("");
                    break;

                case 2:
                    current = Double.parseDouble(answer.getText());
                    previous = previous - current;

                    answer.setText("");
                    break;

                case 3:
                    current = Double.parseDouble(answer.getText());
                    previous = previous * current;
                    answer.setText("");
                    break;

                case 4:
                    current = Double.parseDouble(answer.getText());
                    if (current == 0) {
                        answer.setText("Can't Divide by zero");
                        break;
                    }
                    previous = previous / current;
                    answer.setText("");
                    break;
                default:
                    previous = Double.parseDouble(answer.getText());

                    answer.setText("");
                    break;
            }
            opretion = 1;
        } else {
            answer.setText("Enter Valid Inputs");
        }
    }

    private void allClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_allClearActionPerformed
        // TODO add your handling code here:
        previous = 0;
        current = 0;
        opretion = 0;
        answer.setText("");
    }// GEN-LAST:event_allClearActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "4");

    }

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "5");

    }

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:

        answer.setText(answer.getText() + "6");

    }

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        if (checkInput()) {
            switch (opretion) {
                case 1:
                    current = Double.parseDouble(answer.getText());
                    previous = previous + current;

                    answer.setText("");
                    break;

                case 2:
                    current = Double.parseDouble(answer.getText());
                    previous = previous - current;

                    answer.setText("");
                    break;

                case 3:
                    current = Double.parseDouble(answer.getText());
                    previous = previous * current;
                    answer.setText("");
                    break;

                case 4:
                    current = Double.parseDouble(answer.getText());
                    if (current == 0) {
                        answer.setText("Can't Divide by zero");
                        break;
                    }
                    previous = previous / current;
                    answer.setText("");
                    break;
                default:
                    previous = Double.parseDouble(answer.getText());

                    answer.setText("");
                    break;
            }
            opretion = 2;
        } else {
            answer.setText("Enter Valid Inputs");
        }
    }

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
        answer.setText(answer.getText() + "7");
    }

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEightActionPerformed
        // TODO add your handling code here:
        answer.setText(answer.getText() + "8");
    }

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNineActionPerformed
        // TODO add your handling code here:
        answer.setText(answer.getText() + "9");
    }

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnMultiplyActionPerformed
        // TODO add your handling code here:
        if (checkInput()) {
            switch (opretion) {
                case 1:
                    current = Double.parseDouble(answer.getText());
                    previous = previous + current;

                    answer.setText("");
                    break;

                case 2:
                    current = Double.parseDouble(answer.getText());
                    previous = previous - current;

                    answer.setText("");
                    break;

                case 3:
                    current = Double.parseDouble(answer.getText());
                    previous = previous * current;
                    answer.setText("");
                    break;

                case 4:
                    current = Double.parseDouble(answer.getText());
                    if (current == 0) {
                        answer.setText("Can't Divide by zero");
                        break;
                    }
                    previous = previous / current;
                    answer.setText("");
                    break;
                default:
                    previous = Double.parseDouble(answer.getText());

                    answer.setText("");
                    break;
            }
            opretion = 3;
        } else {
            answer.setText("Enter Valid Input");
        }
    }

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        String str = answer.getText();
        if (str.length() != 0) {
            str = str.substring(0, str.length() - 1);
            answer.setText(str);
        } else {
            answer.setText("");
        }

    }

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        if (checkInput()) {
            switch (opretion) {
                case 1:
                    current = Double.parseDouble(answer.getText());
                    previous = previous + current;

                    answer.setText("");
                    break;

                case 2:
                    current = Double.parseDouble(answer.getText());
                    previous = previous - current;

                    answer.setText("");
                    break;

                case 3:
                    current = Double.parseDouble(answer.getText());
                    previous = previous * current;
                    answer.setText("");
                    break;

                case 4:
                    current = Double.parseDouble(answer.getText());
                    if (current == 0) {
                        answer.setText("Can't Divide by zero");
                        break;
                    }
                    previous = previous / current;
                    answer.setText("");
                    break;
                default:
                    previous = Double.parseDouble(answer.getText());

                    answer.setText("");
                    break;
            }
            opretion = 4;
        } else {
            answer.setText("Enter Valid Inputs");
        }
    }

    private void formMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        String str = answer.getText();
        str = str.substring(0, str.length() - 1);
        answer.setText(str);
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void PlusMinusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PlusMinusActionPerformed
        // TODO add your handling code here:
        if (checkInput()) {
            double n = Double.parseDouble(answer.getText());
            n = n * (-1);
            answer.setText(n + "");
        } else {
            System.out.println("Enter Valid Inputs");
        }
    }

    private void btnOne2ActionPerformed(java.awt.event.ActionEvent evt) {
        // code
    }

    private void btnSeven1ActionPerformed(java.awt.event.ActionEvent evt) {
        // code
    }

    // private void allClearMouseEntered(java.awt.event.ActionEvent evt) {
    // // // code
    // }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        // public void run() {
        // new MainGUI().setVisible(true);
        // }
        // });
    }

    public static double previous = 0;
    public static double current = 0;
    public static int opretion = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlusMinus;
    private javax.swing.JButton allClear;
    public javax.swing.JTextField answer;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnDoubleZero;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnOne2;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSeven1;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btndot;
    private javax.swing.JButton clear;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
